apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-redis-exporter
  template:
    metadata:
      labels:
        app: auth-redis-exporter
    spec:
      containers:
        - name: auth-redis-exporter
          image: oliver006/redis_exporter:latest
          ports:
            - containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: auth-redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis-exporter
spec:
  selector:
    app: auth-redis-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9121
      targetPort: 9121
