apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.10.0
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: postgres:postgres@tcp(auth-db:5432)/petshop
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9187
      targetPort: 9187
