apiVersion: v1
kind: Service
metadata:
  name: auth-redis
  labels:
    app: auth-redis
spec:
  ports:
  - name: auth-redis
    port: 6379
    targetPort: 6379
  type: NodePort
  selector:
    app: auth-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-redis
spec:
  selector:
    matchLabels:
      app: auth-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-redis
    spec:
      containers:
      - name: auth-redis
        image: redis:alpine3.16
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    app: auth-redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi