apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: auth-app-autoscale
  name: auth-app-hpa
  namespace: default
spec:
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-app
  name: auth-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: auth-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8012
          env:
            - name: postgres_host
              value: auth-db
            - name: redis_host
              value: auth-redis
          resources:
            requests:
              cpu: 100m
          readinessProbe:
            httpGet:
              path: /health
              port: 8012
          livenessProbe:
            httpGet:
              path: /health
              port: 8012
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-app
  name: auth-app
  namespace: default
spec:
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      port: 8012
      targetPort: 8012
  type: NodePort
