apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-app
  name: auth-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: auth-auth-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8012
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-app
  name: auth-app
  namespace: default
spec:
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      port: 8012
      targetPort: 8012
  type: NodePort
