apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: editor-app
  name: editor-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor-app
  template:
    metadata:
      labels:
        app: editor-app
    spec:
      containers:
        - image: editor-app
          imagePullPolicy: Never
          name: editor-app
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: editor-db-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: editor-db-config
                  key: postgres_password
            - name: CONFIG_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-app-config
                  key: config_host
            - name: CONFIG_APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-app-config
                  key: config_port
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: config-app-config
                  key: config_profile
            - name: CONFIG_URL
              value: "http://$(CONFIG_APP_NAME):$(CONFIG_APP_PORT)"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: editor-app
  name: editor-app
  namespace: default
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: editor-app
  type: ClusterIP